server:
  port: 8888

app:
  api-prefix: /api/v1

spring:
  application:
    name: api-gateway
  codec:
    max-in-memory-size: 10MB
  cloud:
    gateway:
      maxRequestSize: 10MB
      httpclient:
        max-initial-line-length: 50000
        max-header-size: 16000
        response-timeout: 30s
        max-body-size: 10MB
      routes:
        - id: identity_service
          uri: http://localhost:8080
          predicates:
            - Path=${app.api-prefix}/identity/**
          filters:
            - StripPrefix=2
        - id: product_service
          uri: http://localhost:8081
          predicates:
            - Path=${app.api-prefix}/product/**
          filters:
            - StripPrefix=2
        - id: order_service
          uri: http://localhost:8082
          predicates:
            - Path=${app.api-prefix}/order/**
          filters:
            - StripPrefix=2
        - id: favourite_service
          uri: http://localhost:8083
          predicates:
            - Path=${app.api-prefix}/favourite/**
          filters:
            - StripPrefix=2
        - id: inventory_service
          uri: http://localhost:8084
          predicates:
            - Path=${app.api-prefix}/inventory/**
          filters:
            - StripPrefix=2
        - id: payment_service
          uri: http://localhost:8085
          predicates:
            - Path=${app.api-prefix}/payment/**
          filters:
            - StripPrefix=2
        - id: media_service
          uri: http://localhost:8086
          predicates:
            - Path=${app.api-prefix}/media/**
          filters:
            - StripPrefix=2
        - id: search_service
          uri: http://localhost:8087
          predicates:
            - Path=${app.api-prefix}/search/**
          filters:
            - StripPrefix=2