server:
  port: 8085
  servlet:
    context-path: /payment

spring:
  application:
    name: payment-service
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3309/payment_service}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${DBMS_USERNAME}
    password: ${DBMS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    admin:
      auto-create-topics: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

app:
  order-service:
    url: ${OS_CONNECTION:http://localhost:8082/order}

