server:
  port: 8086
  servlet:
    context-path: /media

spring:
  application:
    name: media_service
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  kafka:
    bootstrap-servers: localhost:9092
    admin:
      auto-create-topics: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: media-service-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

minio:
  endpoint: http://localhost:9000
  bucket: ${MINIO_BUCKET}
  access-key: ${MINIO_ACCESS}
  secret-key: ${MINIO_SECRET}